### ISSUE TITLE
Compatible .dbf versions

### ISSUE THREAD

**Issue by simndvr** [luads/php-xbase#108]
Hey! I've been exploring php-xbase recently to extract data from .dbf files, but just to clarify: which DBF versions does this library support? I'm incredibly new to DBase/XBase so some references would also help a lot.

**Comment by gam6itko** [comment]
@simndvr You can find list of compatible databases [here](https://github.com/luads/php-xbase/tree/master/tests/Resources). I will add this info in README ASAP
