### ISSUE TITLE
PHP Fatal error: Uncaught LogicException: Invalid number of bytes in binary string

### ISSUE THREAD

**Issue by gadget00** [luads/php-xbase#111]
Hi all; 

I'm getting this error now when I try to write a new record on a <strike>PDF</strike> **DBF file**:

> PHP Fatal error: Uncaught LogicException: Invalid number of bytes in binary string. Expected: 762. Actual: 796

What does it mean?

**Comment by gam6itko** [comment]
@gadget00 could you provide stck trace or code sample?

**Comment by gadget00** [comment]
here's the stack trace:

`[Wed Feb 09 15:09:26.216711 2022] [php7:error] [pid 6284:tid 1196] [client ::1:34510] PHP Fatal error:  Uncaught LogicException: Invalid number of bytes in binary string. Expected: 762. Actual: 796 in C:\\Bitnami\\wampstack\\apache2\\htdocs\\data\\vendor\\hisamu\\php-xbase\\src\\XBase\\DataConverter\\Record\\DBaseDataConverter.php:76\nStack trace:\n#0 C:\\Bitnami\\wampstack\\apache2\\htdocs\\data\\vendor\\hisamu\\php-xbase\\src\\XBase\\WritableTable.php(251): XBase\\DataConverter\\Record\\DBaseDataConverter->toBinaryString(Object(XBase\\Record\\VisualFoxproRecord))\n#1 C:\\Bitnami\\wampstack\\apache2\\htdocs\\data\\gnc.php(226): XBase\\WritableTable->writeRecord()\n#2 C:\\Bitnami\\wampstack\\apache2\\htdocs\\data\\crear_nuevo_cliente.php(999): include('C:\\\\Bitnami\\\\wamp...')\n#3 {main}\n  thrown in C:\\Bitnami\\wampstack\\apache2\\htdocs\\data\\vendor\\hisamu\\php-xbase\\src\\XBase\\DataConverter\\Record\\DBaseDataConverter.php on line 76, referer: http://localhost/data/nc.php`

**Comment by gadget00** [comment]
@gam6itko I'm very sorry, I don't understand what do you mean.  This code was supposed to insert data in a new row on a DBF.

But hey! I figured out the size of the DBF field was too small for the amount of data coming from PHP and that was the reason for the error.  

I increased the size of the field in the DBF file and problem solved.

This can be closed

**Comment by gam6itko** [comment]
@gadget00 you wrote
> I'm getting this error now when I try to write a new record on a PDF:
PDF? Is it typo?

**Comment by gadget00** [comment]
@gam6itko sorry! I meant "DBF" instead of PDF; I didn't noticed the mistake, I'm so sorry LOL

**Comment by AnwarQasem** [comment]
was there actually found a solution for this ? I'm still getting the same thing.
