### ISSUE TITLE
Can't read or edit data from any dbf files, nor adding new records

### ISSUE THREAD

**Issue by arpyke2006** [luads/php-xbase#112]
Cannot read / edit or add data to newly created or existing dbf file. I get this error:
"Fatal error: Uncaught Exception: Column NAME not found in /vendor/hisamu/php-xbase/src/Table/Table.php on line 58 Exception: Column NAME not found in /vendor/hisamu/php-xbase/src/Table/Table.php on line 58 Call Stack: 0.0027 395672 1. {main}()  2. XBase\Record\DBaseRecord->get()  3. XBase\Table\Table->getColumn() /vendor/hisamu/php-xbase/src/Record/AbstractRecord.php:79"
I can create dbf files.
PHP 7.3 and PHP 7.4
Does anyone else have this problem?

**Comment by gam6itko** [comment]
How did you create these files? Can you upload it here?

**Comment by arpyke2006** [comment]
[test.zip](https://github.com/luads/php-xbase/files/8212573/test.zip)
It creates the .dbf file, but i cannot add new record

**Comment by gam6itko** [comment]
@arpyke2006 fixed in 2.1.1

Also you should not use empty values for DATE columns. Use `null`
