### ISSUE TITLE
TableException: Expected header terminator not present at position 6049

### ISSUE THREAD

**Issue by gadget00** [luads/php-xbase#113]
Hi all,

Somehow now that I open and insert a row in a DBF; the next time I get this exception and is no longer possible to add new records to the Table through php-xbase.  I isolated the issue to immediately after adding a new record and fill the rows with it.  Any clue about the meaning of this error?  Is my insert messing up the header of the DBF?  I used a program VrunFox.exe to do the DBF handling and with it I was able to add a new row; but not in PHP anymore

**Comment by gam6itko** [comment]
@gadget00 did you add new row by php-xbase or another application?

**Comment by gadget00** [comment]
it was via php-xbase.  After adding the new row, I cannot longer add another one; I get this exception

**Comment by gadget00** [comment]
I have version 1.2.1 right now in the production server; working on updating the code to 1.4.0 in my dev environment; never had this error before

**Comment by gam6itko** [comment]
@gadget00 
How often do you insert new rows in file?
Can you give me the file for investigation?

**Comment by gadget00** [comment]
Hello!  Here is a sample DBF file that just had this happened to it.  A few minutes ago I inserted a new record with the PHP code and now I cannot do it and I get the exception error


[demodata.zip](https://github.com/luads/php-xbase/files/8834257/demodata.zip)

**Comment by gam6itko** [comment]
@gadget00 I can't reproduce this bug. Please give me a code example where the bug occurs

**Comment by gadget00** [comment]
heres the Code I'm using https://pastebin.com/p36a8RDT

I'm using 1.4.0; when I do the composer upgrade it doesn't go further than that version.  How can I upgrade to 1.4.1?

**Comment by gam6itko** [comment]
@gadget00 There is so many fixes since 1.2.1. Better way to solve the issue is the upgrade to 1.4.1. There was so many fixes since 1.2.1...

**Comment by gadget00** [comment]
I just upgraded my code to the current version and forgot about this error.  Maybe this can be closed?
