### ISSUE TITLE
moveTo($offset) gives the wrong row with some DBF files

### ISSUE THREAD

**Issue by nebojsac** [luads/php-xbase#31]
Hi there,

So, I've been trying to figure out what's happening with little luck. 
I take a DBF file with over 30k rows and loop over it 1000 rows at a time, and the further it gets the more overlap I get with the rows between two loops. 

Between the 6th and 7th loop it's 2 rows of overlap, and between the 30th and 31st it's around 700, out of the 1000 returned per loop. It takes the script I have an offset of 49000 to read all the 33000 rows in the DBF file.

For example, when reading just one row, offsets 40000 and 40001 return the same row.

When I open the file in LibreOffice and with dbview I get the same, correct, row count between them.

I've been trying to debug the script with no luck. Unfortunately I can't give you the original DBF file to debug because of sensitive information in it. However, I am willing to try and find the issue myself if you have some pointers on what the issue could be.

To make matters weirder, if open the DBF file with LibreOffice and just save it, then xbase handles offsets correctly. This makes me assume that there is odd formatting or encoding in the original file which gets squashed once LibreOffice saves it.

Any pointers?

**Comment by nebojsac** [comment]
So, I have investigated this a bit further.
It would seem that DBF files have some "duplicate" rows that are invisible to LibreOffice if it reads it in DBF format. They do show up if you convert the DBF file to CSV before reading (I did this with a small python script, https://gist.github.com/bertspaan/8220892).

At this point I'm not sure if this is an issue with the way LibreOffice handles DBF files, or if it's something to do with xbase.

**Comment by gadget00** [comment]
I think you should check opening the original DBF file directly with a DBF viewer, rather than LibreOffice to see if the duplicates where there in first instance

**Comment by nebojsac** [comment]
LibreOffice is a DBF viewer in that sense. When it's a DBF file I'm opening, the duplicate rows are not there. But that isn't the same as the xbase output, as the output does include the duplicates.

**Comment by gadget00** [comment]
how do you use 

`moveTo($offset)`

what value do you give to that function?? I want to use it but don't know which value to give it, so it can move to the row I want to

**Comment by nebojsac** [comment]
`$offset` is the row you want to move to. So, if you want to keep moving forward, you need to increase the `$offset` since the last time you used it.

**Comment by gadget00** [comment]
but what determines the number of the row? for example, if I want to move to the record where id=1221

**Comment by nebojsac** [comment]
The number of the row is the row in the DBF file. So, if you're looking by ID, you need to first know where that ID is. Which probably means you need to go through the entire file first.

Best way to go about using these files is to import the entire thing into a database table, and then run any SELECT queries on the table itself.

**Comment by gam6itko** [comment]
I don't think it's still actual
