### ISSUE TITLE
Record->forceGetString trims data

### ISSUE THREAD

**Issue by nebojsac** [luads/php-xbase#32]
I don't think manipulation of the content of the file should happen within this script. Trimming should probably happen in userland code. 

For my case, I removed the `trim()` call in `forceGetString()` as it was causing problems with expected offsets. I'm not sure if this could be a widespread issue, but my regular tests, with other files, didn't break when I removed `trim()`.

What do you think?

**Comment by gam6itko** [comment]
To get not trimmed genuine data use this
```php
$this-choppedData['column_name'];
```
