### ISSUE TITLE
Missing columns

### ISSUE THREAD

**Issue by debrouchee** [luads/php-xbase#33]
I import a dbf-file with 65 columns. After the import I miss the last 9 columns. The file is a foxpro-file (with version-number 245 from readHeader-method).

My workaround is a modification of the __construct-method by adding a custom argument named $missingColumns. After that I add this value to the $fieldCount-variable in the readHeader-method:

`$fieldCount = floor(($this->headerLength - ($this->foxpro ? 296 : 33)) / 32);
if ($this->missingColumns) $fieldCount += $this->missingColumns;`

That works for me. Maybe the file file has too much columns?

**Comment by jl401812** [comment]
I know this is an old thread, but if anyone else has this issue, try removing `245` from line 54 of Table.php

`$this->foxpro = in_array($this->version, array(48, 49, 131, 203, 245, 251));`

In my case, this allowed me to correctly import all the right columns.

**Comment by gam6itko** [comment]
Fixed for #75
