### ISSUE TITLE
can not read dbf

### ISSUE THREAD

**Issue by ghopretz** [luads/php-xbase#46]
i have dbf file with 223 columns and 902 records.
i use this library to read in php, but it can not read the records of that dbf file and only can read the columns of that dbf file. why?

**Comment by ghozien** [comment]
[Export Sakernas2017 smt taput.zip](https://github.com/hisamu/php-xbase/files/1275887/Export.Sakernas2017.smt.taput.zip)
this is my file

**Comment by gadget00** [comment]
hi @ghozien ,

did you follow the example?  You need to open the DBF and place a loop in order to read the records:

```
use XBase\Table;

$table = new Table(dirname(__FILE__).'/test.dbf');

while ($record = $table->nextRecord()) {
    echo $record->my_column; //THIS LINE PRINTS THE CONTENT OF EACH COLUMN OF THE RECORD

}
```
