### ISSUE TITLE
$table->writeRecord(); problems

### ISSUE THREAD

**Issue by victortyau** [luads/php-xbase#47]
I cannot save a new record from php into with this $table->writeRecord(); sentence, please help me you guys

**Comment by gadget00** [comment]
I'm having the same problem; is there any way to display an error or something??

**Comment by kingofnull** [comment]
you can use my fork until the project maintainer accept my push request.

https://github.com/kingofnull/php-xbase

**Comment by gadget00** [comment]
Hi, we are still having problems writing in the DBF.  Can somebody please help with this??

**Comment by gam6itko** [comment]
fixed in 1.1.0 see example in `WritableTableTest`
