### ISSUE TITLE
Can't update a single record; always creates a duplicate record with the updated field

### ISSUE THREAD

**Issue by gadget00** [luads/php-xbase#51]
Hi all,

I'm trying to update a single record in the DBF but instead the function writeRecord() keeps adding new lines to the DBF with each update.  Am I using the wrong function?  I don't see either any updateRecord() or anything similar.

Please help; thank you

**Comment by rtfmfm** [comment]
Anyone here? I'd love to get this working...

**Comment by gadget00** [comment]
@hisamu 

bro we need you to take a look at the issues and pull requests. Ok?
irmao, precissamos que vc venha e olhe os problemas e os pull requests. Valeu?

**Comment by hisamu** [comment]
Hey @gadget00,

The _write_ part was a contribution made by another user, so I'm not totally familiar with it. I could help testing it though. I'd just ask for a sample DBF and the code used for the faulty scenario.

**Comment by gadget00** [comment]
Hi @hisamu!  Great that you answered.

I'm attaching the DBF file I'm working on, and the sample code I made to test the writing on it.

Just to remind you, I used the code modified by @kingofnull in this example

[write_example.zip](https://github.com/hisamu/php-xbase/files/1553982/write_example.zip)

**Comment by gadget00** [comment]
Hi all,

did we ever found an option for updating a single row?

**Comment by gam6itko** [comment]
I do not see a sign of duplicate during the testing.

Here is testing script. I run it on v1.1.0.
```php
 public function testDuplicate()
    {
        $REAL_COUNT = 20881;
        $copyTo = $this->duplicateFile(__DIR__."/Resources/NUMETRAN.DBF");
        try {
            $newTable = new WritableTable($copyTo, null, 'CP850');
            $newTable->openWrite();
            self::assertEquals($REAL_COUNT, $newTable->getRecordCount());

            $i = 10;
            while ($record = $newTable->nextRecord()) {
                $record->ultsocio = "00".$i; // string length is 4
                $newTable->writeRecord();
                $i++;
            }

            $newTable->close();

            $table = new Table($copyTo, null, 'CP850');

            $i = 10;
            $count = 0;
            while ($record = $table->nextRecord()) {
                self::assertSame(substr("00".$i, 0, 4), $record->ultsocio);
                $i++;
                $count++;
            }

            self::assertEquals($count, $table->getRecordCount());
            self::assertEquals($REAL_COUNT, $table->getRecordCount());
        } finally {
            unlink($copyTo);
        }
    }
```

**Comment by gadget00** [comment]
Correct; I tested myself now and it its not duplicating anymore.  I'm closing this one
