### ISSUE TITLE
Beware don't trust type in column as INT.

### ISSUE THREAD

**Issue by ethaizone** [luads/php-xbase#53]
This is not real issue for this libary. This library is very good and help my life but some of dbf files that I work with it have some problem.

When they parsed and tell it as Number but in real data has decimal so Right now in my migration script. I must make all of them as FLOAT to MySQL and make second migration to make decision for write correct value to new application.

I read in source code and author use byte reading method so I think this is best solution right now. (I don't know another method too.)

For who that use this library. You must recheck your data before use.

Thank again for making this lib. :)

**Comment by gam6itko** [comment]
Can you provide problematic dbf files for tests ?

**Comment by ethaizone** [comment]
@gam6itko I'm sorry. This issue is long time ago and I don't have data anymore. Actually I shouldn't create issue like this. I should provide more information at that time or not create issue if it's not major problem.
