### ISSUE TITLE
composer install

### ISSUE THREAD

**Issue by blacksenator** [luads/php-xbase#62]
command must be:`

"hisamu/php-xbase":"^1.0.5"`

please correct READ.ME and [https://packagist.org/packages/hisamu/php-xbase](https://packagist.org/packages/hisamu/php-xbase)

**Comment by luads** [comment]
Can you open a PR?

**Comment by gam6itko** [comment]
@blacksenator The documentation is correct. By default composer installs last version. If you need the certain version you can set it in your composer.json file
