### ISSUE TITLE
Can't insert Type Double  (Visual Foxpro)  

### ISSUE THREAD

**Issue by jackieweb** [luads/php-xbase#64]
.dbf (vfp) i'm insert data. 

Example. 
insert value 10.25  in field type double (8,2)   type  B

 data view on browser is   6.0136069851366E-154

**Comment by gam6itko** [comment]
@jackieweb Can you provide database file and code example?

**Comment by jackieweb** [comment]
Thank you for my question . Now i'm not  work programming.

Thank you very much.

Alexander Strizhak

ในวันที่ พ. 12 ก.พ. 2020 เวลา 05:58 Alexander Strizhak <
notifications@github.com> เขียนว่า:
