### ISSUE TITLE
Some columns cannot be read

### ISSUE THREAD

**Issue by Fabricio872** [luads/php-xbase#75]
I have some .dbf files in work which i need to fill the database but one file with memo file while opened with Libre office calc have 12 columns but luads/php-xbase see only 3 of them. I am sending problematic files as an attachment and also here is the link for my testing laravel project for easier simulation of the problem many thanks for any help.

https://github.com/Fabricio872/foxproTest

[foxproTest.zip](https://github.com/luads/php-xbase/files/4138546/foxproTest.zip)

**Comment by gam6itko** [comment]
Сause of error #69. I'ill fix it soon

**Comment by gam6itko** [comment]
@Fabricio872 You can  test it with composer version dev-master#d61a4539f57d65620785604b8b380890225c518e
