### ISSUE TITLE
Can’t insert dates in DBF

### ISSUE THREAD

**Issue by gadget00** [luads/php-xbase#78]
Hi all,

Please guide me into how to insert dates in the DBF files. Every time I add a record, the DBF fields that are of the “Date” value always go either null, 0000/00/00 or with the initial date of unix epoch 31/12/1969. 

Exactly which is the correct way to insert a date in the date field of the DBF file??

 I hope you can help me with this, thanks

**Comment by gam6itko** [comment]
@gadget00 Can you provide database file and code sample?

**Comment by gadget00** [comment]
@gam6itko  sure, here's a DBF sample and the code I use.  It almost always either inserts an empty date, or "12/31/1969".  This issue has bugged me for years, literally.  I hope you can take a look a it and help me fix this

[phpxbase_insert_date_test.zip](https://github.com/luads/php-xbase/files/4181293/phpxbase_insert_date_test.zip)

**Comment by gam6itko** [comment]
@gadget00 Looks like this is a stripped down version of the original file. How many lines were in the original file? What tool did you use to reduce the number of lines?

**Comment by gadget00** [comment]
The original file had over 10,000 lines.  I used a Visual FoxPro CLI to cut off the records and also to scramble the original data a little bit.

**Comment by gam6itko** [comment]
You use wrong date format to set date
```php
$record->fecnacim =  date("d/m/Y",$nacimiento);
```
Here `strtotime` recognizes the date as `m/d/Y`.
https://github.com/luads/php-xbase/blob/85fe93d63b02e16b7f6378170f4aa64be4b6af3a/src/XBase/Record.php#L451

To solve this problem you should set date in `m/d/Y` format.

```php
$record->fecnacim =  date("m/d/Y",$nacimiento);
```

I'm going to add support for DateTime object for `D` and `T` columns.
```php
$record->setDate($record->getColumn('dt'), new \DateTime('1970-01-03'));
$record->dt = \DateTime::createFromFormat("U", 777859200);

$dateString = $record->getDateTimeObject('dt')->format('m/d/Y')
```

Will this feature is useful for you?

**Comment by gadget00** [comment]
@gam6itko  it would be VERY useful indeed; as long as the DBF format supports datetime; does it?

**Comment by gam6itko** [comment]
@gadget00  [field-types doc](http://www.independent-software.com/dbase-dbf-dbt-file-format.html#field-types). DateTime (T) type supports by FoxPro. dBase has only Date (D) type. We could convert it to php DateTime object for fore convenient usage (format, convert, etc)

**Comment by gam6itko** [comment]
@gadget00  Did i help you? Can close the issue? If you want get DATE (D) as php DateTime object you should update libradry to 1.1@dev

**Comment by gadget00** [comment]
it worked perfectly; thank you very much for picking up the project and start closing issues!
