### ISSUE TITLE
Missing Column.php?

### ISSUE THREAD

**Issue by xombie4less** [luads/php-xbase#80]
I just downloaded this package and noticed that there is no `src/XBase/Column.php` file, but it is referenced in the `test-memory.php` script and was in previous releases.  Is there a new path to `Column.php`?  

Thanks in advance!

**Comment by gam6itko** [comment]
If you need example how to work with library you should look at the files in the `tests` folder. `XBase\Column` class replaced by `XBase\Column\DbaseColumn`.
