### ISSUE TITLE
Error while reading Memo fields for VisualFoxPro

### ISSUE THREAD

**Issue by kovinet** [luads/php-xbase#81]
I have tested this lib with VisualFoxPro database which has one field of type memo. If I read the db without accessing memo field with getter, it works fine. But if I also try to access memo there are few bugs.

After reading couple of hundred lines successfully it start throwing this errors:

> unpack(): Type N: not enough input, need 4, have 0

This is the exact warning:

> PHP Warning:  unpack(): Type N: not enough input, need 4, have 0 in /php-xbase/src/XBase/Memo/FoxproMemo.php on line 39

After this warning happens from that moment on all future rows in a while loop are corrupted (memo is not read and there is warning for each line).

So I can only read X lines, but after that it stops working.

**Comment by kovinet** [comment]
I have tracked down the error to `src/XBase/Memo/FoxproMemo.php` where `$pointer` which is passed to `get($pointer)` function becomes negative, which in turn calculates wrong negative `$offset` for `fseek()`

I will try to solve it and provide PR.

**Comment by gam6itko** [comment]
@kovinet can you give me the file?

**Comment by kovinet** [comment]
I would have to clean it up, because it has personal information which I can't share ...

Problem seems to be in this line:

> $decPointer = unpack('s', $pointer)[1];

s - signed short (always 16 bit, machine byte order)

So after certain offset is reached (limit of 16 bit) it becomes negative.

**Comment by kovinet** [comment]
Using upper case 'S' (unsigned) seems to work better.

**Comment by gam6itko** [comment]
@kovinet will you create a PR or should I make these edits?

**Comment by kovinet** [comment]
I will create it. Using unsigned short is not the solution, it fails after the limit is reached, still, FYI.

**Comment by kovinet** [comment]
#82

**Comment by gam6itko** [comment]
@kovinet thanks for your contribution
