### ISSUE TITLE
cannot handle datatype I

### ISSUE THREAD

**Issue by imidimi** [luads/php-xbase#89]
For all the data types its working fine, but as soon `I` data type comes in any table it gives this error. Can you please review it?

**Comment by gam6itko** [comment]
Can you provide file and code example?

**Comment by imidimi** [comment]
Getting all fields for the table first. Then assigning them values.
[SALES.zip](https://github.com/luads/php-xbase/files/5195300/SALES.zip)


$tableA = get('C:\\pcmrpw\\' . $saleTable);
$allColumns = $tableA->getColumns();

foreach ($allColumns as $key => $column) {
    $allColumns[$key] = isset($_POST[$key]) ? $_POST[$key] : '';
}

$tableB = add('C:\\pcmrpw\\' . $saleTable);
$tableB->openWrite();
$newRecord = $tableB->appendRecord();

foreach ($allColumns as $key => $column) {
    $newRecord->{$key} = isset($_POST[$key]) ? $_POST[$key] : '';
}

$tableB->writeRecord();
$tableB->pack();
$tableB->close();
unset($newRecord);

**Comment by gam6itko** [comment]
@imidimi I'll fix it asap

**Comment by gam6itko** [comment]
fixen in 2267452d19f0acaf456222a9c5e499576dbdc68b
