### ISSUE TITLE
Error in datetimes after updating to 1.3.0

### ISSUE THREAD

**Issue by AgustinNormand** [luads/php-xbase#93]
Hi, 

I'm learning php so maybe this is something easy to resolve but I dont know how to do it.
I'm getting this error since I updated my app that was working fine with the version 1.2.2 of this library:
TypeError: Return value of XBase\DataConverter\Field\VisualFoxpro\DateTimeConverter::fromBinaryString() must implement interface DateTimeInterface or be null, bool returned

/home/agustin/Test/vendor/hisamu/php-xbase/src/XBase/DataConverter/Field/VisualFoxpro/DateTimeConverter.php:31
/home/agustin/Test/vendor/hisamu/php-xbase/src/XBase/DataConverter/Record/DBaseDataConverter.php:100
/home/agustin/Test/vendor/hisamu/php-xbase/src/XBase/DataConverter/Record/DBaseDataConverter.php:57
/home/agustin/Test/vendor/hisamu/php-xbase/src/XBase/Record/RecordFactory.php:27
/home/agustin/Test/vendor/hisamu/php-xbase/src/XBase/Table.php:328

I would appreciate any help, 

Sorry for my English, 

Agustín.

**Comment by gam6itko** [comment]
Hi. Can you provide database file and code to reproduce this bug?

**Comment by ebta** [comment]
I think it's because the value from dbf sometime result in float, I make pull request here #94

**Comment by gam6itko** [comment]
@AgustinNormand you need to update to `dev-master` and make sure it works correct for now.

**Comment by AgustinNormand** [comment]
Thank you, now in dev-master works fine. Regards
