### ISSUE TITLE
Open DBF file in "parallel mode"? (without cloning)

### ISSUE THREAD

**Issue by DierteK** [luads/php-xbase#97]
Hello,

i would like to edit (WritableTable) a dbf file, but the file is already opened by an older application.

With programs like "DBF Viewer 2000" I can easily edit these files. The changes are then also immediately visible in the application.

But XBase creates a copy and then copies it back again. Unfortunately the program cannot handle this. 

Is there any way to open the files directly?

Thanks

**Comment by gam6itko** [comment]
The "clone" approach was made for safety purposes, it allows user to rollback changes in file. If you need this, then I can make a "realtime" approach, which you can set in constructor options.

**Comment by DierteK** [comment]
Would be great if this could be solved in realtime.

Thanks

**Comment by razvanphp** [comment]
I'm also interested in this realtime edit mode... it should be faster that writing the whole file again just to add one new record for example.

In my application I also need a stream returned for downloading, so probably I'll bake something and open a PR if welcomed.

Thank you for your work!

**Comment by gam6itko** [comment]
@razvanphp PR is no needed, I'll do it at the week.

**Comment by gam6itko** [comment]
Use `1.3.2` with code below

```php
$tableWrite = new WritableTable(
    'file.dbf', 
    [
        'encoding' => 'cp866',
        'editMode' => WritableTable::EDIT_MODE_REALTIME,
    ]
);
// do edits
$tableWrite->close();
```

waiting for your feedback

**Comment by DierteK** [comment]
Thanks, works perfectly :-)

I could change a DBF file that was opened by several Foxpro applications (via Windows/CIFS) at the same time and no error occurred. 

One more question:
After an $table->writeRecord(); all 3-digit decimal numbers become 2-digit. And this not only for fields I changed, but also for existing fields.

Is there a solution for this? It is a FoxPro-DBF, field type is numeric 10, 3. 

Thanks

**Comment by gam6itko** [comment]
@DierteK please open a new issue for "10, 3"
