### ISSUE TITLE
writeRecord() changes all decimal digits in the record

### ISSUE THREAD

**Issue by DierteK** [luads/php-xbase#99]
I want to modify an already existing DBF file (FoxBase+/dbase III PLUS). 
But as soon as I save the record with writeRecord(), all numeric fields are written with 2 decimal units, fields with the value 0 are written without decimal units.

Example view of a database:
![decimal](https://user-images.githubusercontent.com/69114693/101734854-35c2f380-3ac1-11eb-8ac7-d711deae5363.png)
The two marked records were written without changes. (just a $table->writeRecord(); without any changes)

Example field information  (first field):
`      [type:protected] => N
            [length:protected] => 14
            [decimalCount:protected] => 3`

Thanks

**Comment by gam6itko** [comment]
@DierteK fixed in 1.3.3
